flipping one thing

diff --git a/scripts/backupStuff b/scripts/backupStuff
--- a/scripts/backupStuff
+++ b/scripts/backupStuff
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+$(/bin/bash -n $0 >> /dev/null 2>&1)
+if [ $? -ne 0 ]; then
+   $(/bin/bash -n $0)
+   echo "This script has syntax errors, try again!"
+   exit 254
+fi
+
 usage() {
   SCRIPT=$(basename $0)
   echo "usage: $SCRIPT DIR_TO_BE_BACKED_UP"
@@ -34,7 +41,7 @@ if [ $(/bin/mount | /bin/grep backup | /usr/bin/wc -l) != 1 ]; then
   exit 257
 fi
 
-if [ $(/usr/bin/rsync -avqn --exclude='._*' --exclude='*.jpg' $SRC $DEST | /usr/bin/wc -l) != 0 ]; then
+if [ $(/usr/bin/rsync -avn --exclude='._*' --exclude='*.jpg' $SRC $DEST | /usr/bin/wc -l) != 0 ]; then
 
   echo "doing the following in 10s. speak now or forever hold your peace."
   echo "rsync -av $SRC $DEST"
@@ -48,9 +55,13 @@ if [ $(/usr/bin/rsync -avqn --exclude='._*' --exclude='*.jpg' $SRC $DEST | /usr/
 
   /bin/chmod -R 0777 $SRC
 
-  /usr/bin/rsync -avn --exclude='._*' --exclude='*.jpg' $SRC $DEST | /usr/bin/mail -s "Automated backup report" justinmhunter@gmail.com
+  /usr/bin/rsync -av --exclude='._*' --exclude='*.jpg' $SRC $DEST | /usr/bin/mail -s "Automated backup report" justinmhunter@gmail.com
 
   echo "done."
   exit 0
+
+else
+
+  echo "no files to rsync. exiting."
 
 fi
